//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/RoboInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RoboInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RoboInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RoboInput"",
    ""maps"": [
        {
            ""name"": ""RoboActions"",
            ""id"": ""083d6dfc-c364-442b-8b32-9c5e1ff370ba"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2236f178-0e87-4e24-ad8c-dc7ad2dd3665"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4b06ebae-c073-4be6-9195-29f2d89df38b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5cde56c-624b-4ae1-88d4-cf18f3ecf7b4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""39604aa9-dc4d-49c0-97f0-4e8462d65ac9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""762c1ff4-7c75-4871-8493-4d72b4d9673c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eaadba92-503a-4d45-bc08-9f01dde8729c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RoboActions
        m_RoboActions = asset.FindActionMap("RoboActions", throwIfNotFound: true);
        m_RoboActions_Move = m_RoboActions.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RoboActions
    private readonly InputActionMap m_RoboActions;
    private List<IRoboActionsActions> m_RoboActionsActionsCallbackInterfaces = new List<IRoboActionsActions>();
    private readonly InputAction m_RoboActions_Move;
    public struct RoboActionsActions
    {
        private @RoboInput m_Wrapper;
        public RoboActionsActions(@RoboInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_RoboActions_Move;
        public InputActionMap Get() { return m_Wrapper.m_RoboActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RoboActionsActions set) { return set.Get(); }
        public void AddCallbacks(IRoboActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_RoboActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RoboActionsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IRoboActionsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IRoboActionsActions instance)
        {
            if (m_Wrapper.m_RoboActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRoboActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_RoboActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RoboActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RoboActionsActions @RoboActions => new RoboActionsActions(this);
    public interface IRoboActionsActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
